### ISSUE TITLE
Example dropping old indexes

### ISSUE THREAD

**Issue by grumpyseal** [Clever/ARCHIVED-mongoose-any-index#8]
Is there any example of dropping old indexes. I did not see an unit test or example code for this functionality.

**Comment by cozmo** [comment]
We no longer maintain or support this package as we've found declarative indexes in application code to be an anti-pattern that becomes hard to maintain very quickly. We also haven't ever run this with recent versions of mongoose so I'm not sure if it is supported in the latest versions. Somehow missed putting a deprecation warning in this repo - I'll fix that now. 

Sorry! Happy to chat more about index management if you want, but I can't recommend using this plugin.

**Comment by grumpyseal** [comment]
Thanks for you input.
